module.exports = function approveReport(data) {
    const productList = data.products.map(product => `
        <tr>
            <td>${product.product_id.name}</td>
            <td>${product.remark}</td>
            <td>${product.qty}</td>
            <td>${product.price.toFixed(2)} LKR</td>
            <td>${(product.type == 1) ? 'Yes' : 'No'}</td>
        </tr>
    `).join('');

    return `
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Invoice</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    margin: 0;
                    padding: 20px;
                    background-color: #f4f4f4;
                }
                .container {
                    max-width: 800px;
                    margin: 0 auto;
                    background-color: #fff;
                    padding: 20px;
                    border-radius: 10px;
                    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                }
                .invoice-header {
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                    margin-bottom: 20px;
                }
                .invoice-header img {
                    max-width: 150px;
                    margin-right: auto;
                }
                .invoice-header h1 {
                    margin-left: auto;
                }
                .invoice-details {
                    margin-bottom: 14px;
                }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    margin-bottom: 20px;
                }
                th, td {
                    padding: 8px;
                    text-align: left;
                    font-size: 14px;
                }
                th {
                    background-color: #f2f2f2;
                }
                .invoice-footer {
                    margin-top: 20px;
                    text-align: right;
                    font-size: 14px;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="invoice-header">
                    <img src="https://prologics.lk/assets/img/logo.png" alt="Ferentino Logo">
                    <h4>Purches Order - ${data.po.UUID}</h4>
                </div>
                <div class="invoice-details">
                    <p><strong>Effected Date:</strong> ${data.po.effectedDate}</p>
                    <p><strong>Expected Delivery Date:</strong> ${data.po.expectedDeliveryDate}</p>
                    <p><strong>Billing Address:</strong> ${data.po.billingAddress}</p>
                    <p><strong>Warehouse:</strong> ${data.po.warehouse}</p>
                    <p><strong>Customer Ref:</strong> ${data.po.customerRef}</p>
                    <p><strong>Remark:</strong> ${data.po.remark}</p>
                    <p><strong>Created User:</strong> ${data.po.createdUser}</p>
                </div>
                <table>
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Remarks</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Free Issue</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${productList}
                    </tbody>
                </table>
                <div class="invoice-footer">
                    <p>PO generated by Prologics.</p>
                </div>
            </div>
        </body>
        </html>
    `;
};
